export const HIGH_COURT_CASE_TYPES = [
  "ARB. A. (COMM.)",
  "ARB.A.",
  "ARB.P.",
  "BAIL APPLN.",
  "C.A.(COMM.IPD-PAT)",
  "C.A.(COMM.IPD-TM)",
  "CA (COMM.IPD-CR)",
  "CCP(CO.)",
  "CEAC",
  "CHAT.A.C.",
  "CHAT.A.REF",
  "CM(M)",
  "CM(M)-IPD",
  "CMI",
  "CO.APPL.(M)",
  "CO.APP.",
  "CO.A(SB)",
  "CO.PET.",
  "CONT.APP.(C)",
  "CONT.CAS(C)",
  "CONT.CAS.(CRL)",
  "CRL.A.",
  "CRL.C.REF.",
  "CRL.L.P.",
  "CRL.M.C.",
  "CRL.O.(CO.)",
  "CRL.REF.",
  "CRL.REV.P.",
  "CS(COMM)",
  "CS(OS)",
  "CUS.A.C.",
  "CUSAA",
  "CUSTOM A.",
  "C.O. (COMM.IPD-TM)",
  "C.O.(COMM.IPD-CR)",
  "C.O.(COMM.IPD-PAT)",
  "C.R.P.",
  "DEATH SENTENCE REF.",
  "EFA(COMM)",
  "EFA(OS)",
  "EFA(OS) (COMM)",
  "EL.PET.",
  "EX.F.A.",
  "EX.P.",
  "EX.S.A.",
  "FAO",
  "FAO (COMM)",
  "FAO-IPD",
  "FAO(OS)",
  "FAO(OS) (COMM)",
  "I.P.A.",
  "ITA",
  "LA.APP.",
  "LPA",
  "MAC.APP.",
  "MAT.APP.",
  "MAT.APP.(F.C.)",
  "MISC. APPEAL(PMLA)",
  "O.M.P.",
  "O.M.P. (COMM)",
  "O.M.P. (E) (COMM.)",
  "O.M.P. (MISC.)",
  "O.M.P. (T) (COMM.)",
  "O.M.P.(EFA)(COMM.)",
  "O.M.P.(I)",
  "O.M.P.(I) (COMM.)",
  "O.M.P.(MISC.)(COMM.)",
  "O.M.P.(T)",
  "OMP (CONT.)",
  "OMP (ENF.) (COMM.)",
  "RC.REV.",
  "RC.S.A.",
  "RFA",
  "RFA(COMM)",
  "RFA-IPD",
  "RFA(OS)",
  "RFA(OS)(COMM)",
  "RSA",
  "SERTA",
  "ST.APPL.",
  "ST.REF.",
  "TEST.CAS.",
  "TR.P.(C.)",
  "TR.P.(CRL.)",
  "VAT APPEAL",
  "W.C.(C)-IPD",
  "W.P.(C)",
  "W.P.(CRL)"
] as const;


export const DELHI_COURT_CASE_TYPES_VALUE_MAPPING = {
  "ARB. A. (COMM.)": 102,
  "ARB.A.": 83,
  "ARB.P.": 40,
  "BAIL APPLN.": 8,
  "C.A.(COMM.IPD-PAT)": 159,
  "C.A.(COMM.IPD-TM)": 160,
  "CA (COMM.IPD-CR)": 161,
  "CCP(CO.)": 59,
  "CEAC": 117,
  "CHAT.A.C.": 94,
  "CHAT.A.REF": 113,
  "CM(M)": 70,
  "CM(M)-IPD": 152,
  "CMI": 79,
  "CO.APPL.(M)": 20,
  "CO.APP.": 75,
  "CO.A(SB)": 78,
  "CO.PET.": 43,
  "CONT.APP.(C)": 95,
  "CONT.CAS(C)": 127,
  "CONT.CAS.(CRL)": 119,
  "CRL.A.": 92,
  "CRL.C.REF.": 36,
  "CRL.L.P.": 97,
  "CRL.M.C.": 28,
  "CRL.O.(CO.)": 108,
  "CRL.REF.": 115,
  "CRL.REV.P.": 105,
  "CS(COMM)": 51,
  "CS(OS)": 122,
  "CUS.A.C.": 116,
  "CUSAA": 15,
  "CUSTOM A.": 86,
  "C.O. (COMM.IPD-TM)": 158,
  "C.O.(COMM.IPD-CR)": 165,
  "C.O.(COMM.IPD-PAT)": 164,
  "C.R.P.": 68,
  "DEATH SENTENCE REF.": 104,
  "EFA(COMM)": 144,
  "EFA(OS)": 73,
  "EFA(OS) (COMM)": 62,
  "EL.PET.": 3,
  "EX.F.A.": 90,
  "EX.P.": 56,
  "EX.S.A.": 91,
  "FAO": 24,
  "FAO (COMM)": 142,
  "FAO-IPD": 148,
  "FAO(OS)": 112,
  "FAO(OS) (COMM)": 67,
  "I.P.A.": 54,
  "ITA": 39,
  "LA.APP.": 9,
  "LPA": 38,
  "MAC.APP.": 58,
  "MAT.APP.": 7,
  "MAT.APP.(F.C.)": 26,
  "MISC. APPEAL(PMLA)": 143,
  "O.M.P.": 4,
  "O.M.P. (COMM)": 64,
  "O.M.P. (E) (COMM.)": 49,
  "O.M.P. (MISC.)": 135,
  "O.M.P. (T) (COMM.)": 100,
  "O.M.P.(EFA)(COMM.)": 65,
  "O.M.P.(I)": 66,
  "O.M.P.(I) (COMM.)": 99,
  "O.M.P.(MISC.)(COMM.)": 123,
  "O.M.P.(T)": 17,
  "OMP (CONT.)": 136,
  "OMP (ENF.) (COMM.)": 50,
  "RC.REV.": 60,
  "RC.S.A.": 25,
  "RFA": 22,
  "RFA(COMM)": 141,
  "RFA-IPD": 146,
  "RFA(OS)": 33,
  "RFA(OS)(COMM)": 52,
  "RSA": 23,
  "SERTA": 98,
  "ST.APPL.": 31,
  "ST.REF.": 109,
  "TEST.CAS.": 53,
  "TR.P.(C.)": 103,
  "TR.P.(CRL.)": 76,
  "VAT APPEAL": 63,
  "W.C.(C)-IPD": 147,
  "W.P.(C)": 134,
  "W.P.(CRL)": 27,
} as const;

export const SUPREME_COURT_CASE_TYPES = [
  "CRIMINAL",
  "CIVIL"
] as const; 


export const HIGH_COURT_CITY = [
  "Delhi",
] as const
