
export const DELHI_COURT_CASE_TYPES_VALUE_MAPPING = {
  "ARB. A. (COMM.)": 102,
  "ARB.A.": 83,
  "ARB.P.": 40,
  "BAIL APPLN.": 8,
  "C.A.(COMM.IPD-PAT)": 159,
  "C.A.(COMM.IPD-TM)": 160,
  "CA (COMM.IPD-CR)": 161,
  "CCP(CO.)": 59,
  "CEAC": 117,
  "CHAT.A.C.": 94,
  "CHAT.A.REF": 113,
  "CM(M)": 70,
  "CM(M)-IPD": 152,
  "CMI": 79,
  "CO.APPL.(M)": 20,
  "CO.APP.": 75,
  "CO.A(SB)": 78,
  "CO.PET.": 43,
  "CONT.APP.(C)": 95,
  "CONT.CAS(C)": 127,
  "CONT.CAS.(CRL)": 119,
  "CRL.A.": 92,
  "CRL.C.REF.": 36,
  "CRL.L.P.": 97,
  "CRL.M.C.": 28,
  "CRL.O.(CO.)": 108,
  "CRL.REF.": 115,
  "CRL.REV.P.": 105,
  "CS(COMM)": 51,
  "CS(OS)": 122,
  "CUS.A.C.": 116,
  "CUSAA": 15,
  "CUSTOM A.": 86,
  "C.O. (COMM.IPD-TM)": 158,
  "C.O.(COMM.IPD-CR)": 165,
  "C.O.(COMM.IPD-PAT)": 164,
  "C.R.P.": 68,
  "DEATH SENTENCE REF.": 104,
  "EFA(COMM)": 144,
  "EFA(OS)": 73,
  "EFA(OS) (COMM)": 62,
  "EL.PET.": 3,
  "EX.F.A.": 90,
  "EX.P.": 56,
  "EX.S.A.": 91,
  "FAO": 24,
  "FAO (COMM)": 142,
  "FAO-IPD": 148,
  "FAO(OS)": 112,
  "FAO(OS) (COMM)": 67,
  "I.P.A.": 54,
  "ITA": 39,
  "LA.APP.": 9,
  "LPA": 38,
  "MAC.APP.": 58,
  "MAT.APP.": 7,
  "MAT.APP.(F.C.)": 26,
  "MISC. APPEAL(PMLA)": 143,
  "O.M.P.": 4,
  "O.M.P. (COMM)": 64,
  "O.M.P. (E) (COMM.)": 49,
  "O.M.P. (MISC.)": 135,
  "O.M.P. (T) (COMM.)": 100,
  "O.M.P.(EFA)(COMM.)": 65,
  "O.M.P.(I)": 66,
  "O.M.P.(I) (COMM.)": 99,
  "O.M.P.(MISC.)(COMM.)": 123,
  "O.M.P.(T)": 17,
  "OMP (CONT.)": 136,
  "OMP (ENF.) (COMM.)": 50,
  "RC.REV.": 60,
  "RC.S.A.": 25,
  "RFA": 22,
  "RFA(COMM)": 141,
  "RFA-IPD": 146,
  "RFA(OS)": 33,
  "RFA(OS)(COMM)": 52,
  "RSA": 23,
  "SERTA": 98,
  "ST.APPL.": 31,
  "ST.REF.": 109,
  "TEST.CAS.": 53,
  "TR.P.(C.)": 103,
  "TR.P.(CRL.)": 76,
  "VAT APPEAL": 63,
  "W.C.(C)-IPD": 147,
  "W.P.(C)": 134,
  "W.P.(CRL)": 27,
} as const;

export const SUPREME_COURT_CASE_TYPES = [
  "CRIMINAL",
  "CIVIL"
] as const; 


export const HIGH_COURT_CITY = [
  "Delhi",
  "Mumbai"
] as const

export const BOMBAY_HIGH_COURT_BENCH = [
   "Appellate Side,Bombay",
   "Bench at Aurangabad",
   "Bench at Nagpur",
   "Bombay High Court,Bench at Kolhapur",
   "Original Side,Bombay",
   "High court of Bombay at Goa",
   "Special Court (TORTS) Bombay"
] as const


export const APPELLATE_BOMBAY_COURT_CASE_TYPES_VALUE_MAPPING = {
  // Existing mappings (retained)
  "ABA(Cr. Anticipatory Bail AppIn.)": 332,
  "ALP(AppIn for Leave to Appeal(PVT..))": 335,
  "ALS(AppIn For Leave to Appeal(STATE))": 334,
  "AO(Appeal from Order)": 3,
  "APEAL(Cr. Appeal)": 310,
  "APL(Criminal AppIn. U/s 482)": 330,
  "APPA(Cr. Application in Appeal)": 321,
  "APPCO(Application In Cr. Conf.)": 327,
  "APPCP(Application In Cr. Cont. Petn.)": 326,
  "APPCR(Application In Cr. Reference)": 324,
  "APPI(Application In Cr. PIL)": 325,
  "APPLN(Cr. Application)": 302,
  "APPP(Cr. Application in Application)": 323,
  "APPR(Cr. Application in Revision)": 322,
  "APPSC(Application In Cr. SUO-MOTO CONP)": 329,
  "APPW(Cr. Application in Writ Petition)": 320,
  "ARA(Arb. Appeal u/s 37 of Arb. Conc. 96)": 15,
  "ARP(Arbitration Petition)": 13,
  "AULPA(LPA(AURANGABAD))": 99,
  "BA(Criminal Bail Appln.)": 331,
  "CA(Civil Application)": 18,
  "CAA(Civil Application in AO)": 32,
  "CAC(Civil Application in CRA)": 35,
  "CAE(Civil Application in C.REF)": 50,
  "CAF(Civil Application in FA)": 31,
  "CAFM(Civil Application In FEMA)": 67,
  "CAI(Civil Application in PIL)": 49,
  "CAL(Civil Application in LPA)": 34,
  "CAM(Civil Application in FCA)": 36,
  "CAN(Civil Application in CP)": 37,
  "CAO(CA in Cth.(MCA/TXA/CA/FERA))": 41,
  "CAP(Civil Appl. in ARP)": 39,
  "CAPL(Contempt Appeal)": 12,
  "CAR(Civil Appln. in ARA)": 40,
  "CAS(Civil Application in SA)": 33,
  "CAT(Civil Application in CAPL)": 38,
  "CAW(Civil Application in WP)": 30,
  "CAY(Civil Application in FERA)": 60,
  "CCAPL(COMMERCIAL CONTEMPT APPEAL)": 344,
  "CCNO(Supreme Ct. C. C. NO.)": 57,
  "CCNO(Supreme Ct. Cr. C. C. NO.)": 318,
  "CCPDJ(CIVIL CONTEMPT PETITION BY DISTRICT JUDICIARY)": 348,
  "COARA(COMMERCIAL ARBITRATION APPEAL)": 340,
  "COARP(COMMERCIAL ARBITRATION PETITION)": 342,
  "COMAC(COMMERCIAL AC)": 341,
  "COMCP(COMMERCIAL CONTEMPT PETITION)": 343,
  "COMFA(COMMERCIAL FA)": 339,
  "COMRP(REVIEW PETITION IN COMMERCIAL FA/ARA/AO/ARP/CP/CA)": 345,
  "CONF(Cr. Confirmation Case)": 301,

  // New mappings from the images (added)
  "CONP(Cr. Contempt Petition)": 312,
  "COXOB(CROSS OBJECTION IN COMMERCIAL FA/ARA/AO/ARP/CP/CA)": 346,
  "CP(Cont. Petition)": 10,
  "CRA(Civil Revision Application)": 7,
  "C.REF(Civil References)": 9,
  "CRPIL(Public Interest Litigation)": 319,
  "CRR(Court Receiver Report)": 63,
  "FA(First Appeal)": 2,
  "FAG(First Appeal (GOA))": 98,
  "FCA(Family Court Appeal)": 8,
  "FEMA(FEMA APPEAL)": 66,
  "FERA(FERA Appeal)": 58,
  "F.NO.(F.NO.)": 349,
  "IA(Supreme Ct. Cr. Interlocutory Application)": 316,
  "IA(CRI-INTERIM APPLICATION)": 337,
  "IA(INTERIM APPLICATION)": 69,
  "IA(Supreme Ct. Interlocutory Application)": 55,
  "LPA(Letter Patent Appeal)": 5,
  "MCA(Misc.Civil Application)": 11,
  "MPA(Marriage Petition(A))": 62,
  "PIL(Public Interest Litigation)": 6,
  "RAP(Review Petition in ARA)": 29,
  "RC(Rejected Case)": 43,
  "REF(Cr. Reference)": 311,
  "REVN(Cr. Revision Appln.)": 309,
  "REVW(Criminal Review)": 328,
  "RPA(Review Petn. in AO)": 21,
  "RPC(Review Petn. in CRA)": 24,
  "RPF(Review Petn. in FA)": 20,
  "RPFM(Review Petition In FEMA Appeal)": 68,
  "RPI(Review Petition In PIL)": 51,
  "RPIA(REVIEW PETITION IN IA)": 70,
  "RPL(Review Petn. in LPA)": 23,
  // New mappings from latest images
  "RPM(Review Petn. in FCA)": 25,
  "RPN(Review Petn. in CP)": 26,
  "RPR(Review Petn. in ARP)": 28,
  "RPS(Review Petn. in SA)": 22,
  "RPT(Review Petn. in CAPL)": 27,
  "RPV(Review Petition in MCA)": 48,
  "RPW(Review Petn. in WP)": 19,
  "SA(Second Appeal)": 4,
  "SCAP(Supreme Ct. Civil Appeal)": 53,
  "SCAP(Supreme Ct. Criminal Appeal)": 314,
  "SCCA(CA for Leave to Appeal to Supreme Court)": 16,
  "SCCP(Supreme Ct. Contempt Petition)": 56,
  "SCCP(Supreme Ct. Cr. Contempt Petition)": 317,
  "SCMP(Supreme Ct. Cr. Misc. Petition)": 315,
  "SCMP(Supreme Ct. Misc. Petition)": 54,
  "SCTP(Supreme Ct. Transfer Petition)": 61,
  "SCTP(Supreme Ct. Transfer Petition(CR))": 333,
  "SLP(Supreme Ct. Special Leave Petition)": 52,
  "SLP(Supreme Ct. Cr. Special Leave Petition)": 313,
  "SMAP(Cr. Suo-Motu Application)": 304,
  "SMCP(Cr. Suo-Motu Contempt Petn.)": 307,
  "SMCPC(Civil Suo Motu Contempt Petition)": 347,
  "SMP(Suo-Motu Cr. PIL)": 336,
  "SMP(Suo-Moto Petition)": 59,
  "SMPIL(Suo Motuo PIL)": 65,
  "SMRN(Cr. Suo-Motu Revision Appln.)": 306,
  "SMWP(Suo Motu Writ Petition)": 64,
  "SMWP(Cr. Suo-Motu Writ Petition)": 305,
  "SOMO(Cr. Suo-Motu Petition)": 303,
  "SPLCA(Special Civil Application)": 17,
  "TXA(Tax Appeal)": 14,
  "WP(Writ Petition)": 1,
  "WP(Cr. Writ Petition)": 308,
  "WPA(WRIT PETITION - AURANGABAD)": 45,
  "WPG(WRIT PETITION - GOA)": 46,
  "WPN(WRIT PETITION - NAGPUR)": 47,
  "XFER(TRANSFER MATTER)": 44,
  "XOB(Cross Objection Stamp)": 42
} as const;


export const AURANGABAD_BOMBAY_HIGH_COURT_CASE_TYPES_VALUE_MAPPING = {
  // Existing mappings (retained)
  "ABA(ANTICIPATORY BAIL APPLICATION)": 319,
  "ALP(Appln. for leave to Appeal by Pvt. Party)": 317,
  "ALS(Appln. for leave to Appeal by State)": 316,
  "AO(Appeal from Order)": 6,
  "APEAL(criminal Appeal)": 305,
  "APPLN(Criminal Application)": 302,
  "BA(BAIL APPLICATION)": 318,
  "CA(Chill Application)": 8,
  "CAP(Company Appeal)": 58,
  "CAPL(Contempt Appeal)": 9,
  "CARAP(Commercial Arbitration Application)": 72,
  "CARBA(Commercial Arbitration Appeal)": 71,
  "CEA(CENTRAL EXCISE APPEAL)": 65,

  // New mappings from images
  "CMA(Company Application)": 56,
  "CMP(COMPANY PETITION)": 53,
  "COMP(Commercial Appeal)": 73,
  "CONF(Criminal Confirmation Case)": 306,
  "CONP(Criminal Contempt Petition)": 309,
  "CP(Cont. Petition)": 7,
  "CRA(CRA)": 22,
  "CRF(Civil References)": 24,
  "CRPIL(Criminal Public Interest Litigation)": 315,
  "CRSMP(Criminal SUO-MOTO PUBLIC INTEREST LITIGATION)": 321,
  "CSA(CUSTOMS APPEAL)": 64,
  "EP(Election petition)": 32,
  "EPAP(Application in EP)": 61,
  "FA(First Appeal)": 2,
  "FCA(Family Court Appeal)": 11,
  "ITA(INCOME TAX APPEAL)": 66,
  "LPA(Letter Patent Appeal)": 3,
  "MCA(Misc.Civil Application)": 10,
  "MPA(Marriage Petition)": 41,
  "MVATA(MAH. VALUE ADDED TAX APPEAL)": 70,
  "PIL(Public Interest Litigation)": 59,
  "RA(Review Application (Civil))": 40,
  "RC(Rejected Case)": 30,
  "REC(RECRIMINATION NO)": 47,
  "REF(Criminal Reference)": 307,
  "REVN(Criminal Revision Application)": 304,
  "REVW(Criminal Review Application)": 314,
  "SA(Second Appeal)": 4,
  "SCCA(Supreme Court Civil Appeal)": 25,
  "SMAP(Criminal Suo-Motu Application)": 310,
  "SMC(SUO MOTO (CP))": 38,
  "SMCP(Criminal Suo-Motu Contempt Petition)": 313,
  "SMPIL(SUO MOTO (PIL))": 69,
  "SMR(SUO MOTO REVISION)": 49,
  "SMRN(Criminal Suo-Motu Revision Application)": 312,
  "SMW(SUO MOTO (WP))": 36,
  "SMWP(Criminal Suo-Motu Writ Petition)": 311,
  "SN(Stamp Number)": 301,
  "SOMO(Criminal Suo-Motu Petition)": 308,
  "SPLCA(Special Civil Application)": 26,
  "STA(Sales Tax Application)": 63,
  "STAPL(SALES TAX APPEAL)": 68,
  "TA(Tax Appeal)": 50,
  "WP(Writ Petition)": 1,
  "WP(Criminal Writ Petition)": 303,
  "WTA(Wealth Tax Appeal)": 67,
  "XAP(Cross Appeal)": 60,
  "X-APL(Cross Appeal)": 31,
  "XFER(TRANSFER MATTER)": 33,
  "X-OBJ(X-Objection)": 27
} as const;


export const NAGPUR_BOMBAY_HIGH_COURT_CASE_TYPES_VALUE_MAPPING = {
  // Existing mappings (retained)
  "AA(Arbitration Appeals)": 40,
  "ABA(Cr. Anticipatory Bail Applications)": 332,
  "AO(Appeal from Order)": 1,
  "APEAL(Criminal Appeal)": 301,
  "APL(Cr. Application U/s 482)": 333,
  "APPA(Cr. Application in Appeal)": 321,
  "APPCO(Application in Cr. Conf.)": 327,
  "APPCP(Application in Cr. Cont. Petn.)": 326,
  "APPCR(Application in Cr. Reference)": 324,
  "APPLE(Criminal Appln. of Bail)": 330,
  "APPLN(Criminal Application)": 302,
  "APPP(Cr. Application in Application)": 323,
  "APPR(Cr. Application in Revision)": 322,
  "APPW(Cr.Application in Writ Petition)": 320,
  "ARA(Arbitration application)": 2,
  "ARP(Arbitration Petition)": 3,

  // New mappings from images
  "BA(Cr. Bail Applications)": 331,
  "CA(Civil Application)": 5,
  "CAA(Civil Application in AO)": 43,
  "CAC(Civil Application in CRA)": 46,
  "CAE(Civil Application in Civil Reference)": 47,
  "CAF(Civil Application in FA)": 42,
  "CAL(Company Application)": 6,
  "CALCR(Company Applications (Criminal))": 7,
  "CAM(Civil Application in AA)": 49,
  "CAN(Civil Application in CP)": 48,
  "CAO(CA IN OTHERS (MCA/EP/CA/XOB/CMP))": 52,
  "CAP(Company Appeal)": 8,
  "CAPL(CUSTOM APPEAL)": 36,
  "CAS(Civil Application in SA)": 44,
  "CAT(Civil Application in Tax Matters)": 50,
  "CAW(Civil Application in WP)": 41,
  "CAZ(Civil Application in LPA)": 45,
  "CEL(CENTRAL EXCISE APPEAL)": 9,
  "CER(Central Excise Reference)": 10,
  "CMP(Company Petition)": 11,
  "COMP(Commercial Appeal)": 51,
  "CONF(Criminal Confirmation Case)": 303,
  "CONP(Criminal Contempt Petition)": 304,
  "CP(Cont. Petition)": 12,
  "CPL(Contempt Appeal)": 13,
  "CRA(Civil Revision Application)": 14,
  "C.REF(Civil References)": 4,
  "CRPIL(Cr. Public Interest Litigation)": 353,
  "CS(Civil Suits (Transfer Civil Suit))": 15,
  "EDR(Estate Duty Reference)": 16,
  "EP(Election petition)": 17,
  "FA(First Appeal)": 18,
  "FCA(Family Court Appeal)": 19,
  "GTA(Gift Tax application)": 20,
  "GTB(Gift Tax Reference)": 21,
  "GTR(Gift Tax Reference)": 21,
  "ITA(Income tax application)": 22,
  "ITL(INCOME TAX APPEAL)": 23,
  "ITR(Income tax reference)": 24,
  "LPA(Letter Patent Appeal)": 25,
  "MCA(Misc.Civil Application)": 26,
  "OLR(Official Liquidator Report)": 27,
  "PIL(Public Interest Litigation)": 53,
  "RAP(Review Petn. in ARA)": 65,
  "RC(Rejected Case)": 30,
  "REF(Criminal Reference)": 305,
  "REVN(Criminal Revision Application)": 306,
  "RPA(Review Petn. in AO)": 57,
  "RPC(Review Petn. in CRA)": 60,
  "RPC.(Review Petn. in FCA)": 61,
  "RPF(Review Petn. in FA)": 56,
  "RPL(Review petn. in LPA)": 59,
  "RPN(Review Petn. in CP)": 62,
  "RPR(Review Petn. in ARP)": 64,
  "RPS(Review Petn. in SA)": 58,
  "RPT(Review Petn. in CAPL)": 63,
  "RPW(Review petin.in WP)": 55,
  "SA(Second Appeal)": 29,
  "SMAP(Cr. Suo Motu Application)": 338,
  "SMAP(Suo Motu Application)": 70,
  "SMC(Suo Motu Contempt Petition)": 69,
  "SMCP(Cr. Suo Motu Contempt Petition)": 337,
  "SMP(Suo Motu Cr PIL)": 335,
  "SMPIL(Suo Motu PIL)": 67,
  "SMWP(Suo Motu Cr. Writ Petition)": 336,
  "SMWP(SM - W.P.)": 310,
  "SMWP(Suo Motu Writ Petition)": 68,
  "SN(Stamp Number (Crim))": 311,
  "SPLCA(Special Civil Application)": 31,
  "STA(SALES TAX APPLICATION)": 38,
  "STR(SALES TAX REFERENCE)": 37,
  "STXA(Sales Tax Appeal)": 39,
  "WP(Criminal Writ Petition)": 313,
  "WP(Writ Petition)": 32,
  "WTA(Wealth Tax application)": 33,
  "WTL(Wealth Tax AreaI)": 28,
  "WTR(Wealth Tax reference)": 34,
  "XOB(Cross Objection)": 35
} as const;


 export const KOLHAPUR_BOMBAY_HIGH_COURT_CASE_TYPES_VALUE_MAPPING = {
  "ABA(Cr. Anticipatory Bail AppIn.)": 332,
  "ALP(AppIn for Leave to Appeal(PVT.))": 335,
  "ALS(AppIn For Leave to Appeal(STATE))": 334,
  "AC(Appeal from Order)": 3,
  "APEAL(Cr. Appeal)": 310,
  "APL(Criminal AppIn. U/s 482)": 330,
  "APPA(Cr. Application in Appeal)": 321,
  "APPCO(Application In Cr. Conf.)": 327,
  "APPCP(Application In Cr. Cont. Petn.)": 326,
  "APPCR(Application In Cr. Reference)": 324,
  "APPI(Application In Cr. PIL)": 325,
  "APPLN(Cr. Application)": 302,
  "APPP(Cr. Application in Application)": 323,
  "APPR(Cr. Application in Revision)": 322,
  "APPSC(Application In Cr. SUO-MOTO CONP)": 329,
  "APPW(Cr. Application in Writ Petition)": 320,
  "ARA(Arb. Apeal u/s 37 of Arb. Conc. 96)": 15,
  "ABP(Arbitration Petition)": 13,
  "ARP(Arbitration Petition)": 13,
  "AULPA(LPA(AURANGABAD))": 99,
  "BA(Criminal Bail Appln.)": 331,
  "CA(Civil Application)": 18,
  "CAA(Civil Application in AO)": 32,
  "CAC(Civil Application in CRA)": 35,
  "CAE(Civil Application in C.REF)": 50,
  "CAF(Civil Application in FA)": 31,
  "CAFM(Civil Application in FEMA)": 67,
  "CAI(Civil Application in PIL)": 49,
  "CAL(Civil Application in LPA)": 34,
  "CAM(Civil Application in FCA)": 36,
  "CAN(Civil Application in CP)": 37,
  "CAO(CA in Oth.(MCA/TXA/CA/FERA))": 41,
  "CAP(Civil Appl. In ARP)": 39,
  "CAPL(Contempt Appeal)": 12,
  "CAR(Civil Appln. in ARA)": 40,
  "CAS(Civil Application in SA)": 33,
  "CAT(CNII Application in CAPL)": 38,
  "CAW(CNII Application in WP)": 30,
  "CAY(CNII Application in FERA)": 60,
  "CCAPL(COMMERCIAL CONTEMPT APPEAL)": 344,
  "CCNO(Supreme Ct. C. C. NO.)": 57,
  "CCNO(Supreme Ct. Cr. C. C. NO.)": 318,
  "CCPDJ(CIVIL CONTEMPT PETITION BY DISTRICT JUDICIARY)": 348,
  "CEXA(CENTRAL EXISE APPEAL)": 624,
  "COARA(COMMERCIAL ARBITRATION APPEAL)": 340,
  "COARP(COMMERCIAL ARBITRATION PETITION)": 342,
  "COMAC(COMMERICAL AC)": 341,
  "COMCP(COMMERCIAL CONTEMPT PETITION)": 343,
  "COMFA(COMMERCIAL FA)": 339,
  "COMRP(REVIEW PETITION IN COMMERCIAL FA/ARA/AO/ARP/CP/CA)": 345,
  "CONF(Cr. Confirmation Case)": 301,
  "CONP(Cr. Contempt Petition)": 312,
  "COXOB(CROSS OBJECTION IN COMMERCIAL FA/ARA/AO/ARP/CP/CA)": 346,
  "CP(Cont. Petition)": 10,
  "CRA(Civil Revision Application)": 7,
  "C.REF(Civil References)": 9,
  "CRPIL(Public Interest Litigation)": 319,
  "CRR(Court Receiver Report)": 63,
  "CUAPP(CUSTOM APPEAL)": 628,
  "EP(ELECTION PETITION)": 509,
  "FA(First Appeal)": 2,
  "FAG(First Appeal (GOA))": 98,
  "FCA(Family Court Appeal)": 8,
  "FEMA(FEMA APPEAL)": 66,
  "FERA(FERA Appeal)": 58,
  "F.NO.(F.NO.)": 349,
  "IA(INTERIM APPLICATION)": 69,
  "IA(Supreme Ct. Cr. Introlocatory Application)": 316,
  "IA(Supreme Ct. Introlocatory Application)": 55,
  "IA(CRI-INTERIM APPLICATION)": 337,
  "IRXA(INTEREST TAX APPEAL)": 617,
  "ITXA(INCOME TAX APPEAL(IT))": 601,
  "LPA(Letter Patent Appeal)": 5,
  "MCA(Misc.Civil Application)": 11,
  "MPA(Marriage Petition(A))": 62,
  "MVXA(Mah.Value Added Tax Appeal)": 722,
  "PIL(Public Interest Litigation)": 6,
  "RAP(Review Petition in ARA)": 29,
  "RC(Rejected Case)": 43,
  "REF(Cr. Reference)": 311,
  "REVN(Cr. Revision Appln.)": 309,
  "REVW(Criminal Review)": 328,
  "RPA(Review Petn. in AO)": 21,
  "RPC(Review Petn. in CRA)": 24,
  "RPF(Review Petn. in FA)": 20,
  "RPFM(Review Petition In FEMA Appeal)": 68,
  "RPI(Review Petition In PIL)": 51,
  "RPIA(REVIEW PETITION IN IA)": 338,
  "RPL(Review Petn. in LPA)": 23,
  "RPM(Review Petn. in FCA)": 25,
  "RPN(Review Petn. in CP)": 26,
  "RPR(Review Petn. in ARP)": 28,
  "RPS(Review Petn. in SA)": 22,
  "RPT(Review Petn. in CAPL)": 27,
  "RPV(Review Petition in MCA)": 48,
  "RPW(Review Petn. in WP)": 19,
  "SA(Second Appeal)": 4,
  "SCAP(Supreme Ct. Civil Appeal)": 53,
  "SCAP(Supreme Ct. Criminal Appeal)": 314,
  "SCCA(CA for Leave to Appeal to Supreme Court)": 16,
  "SCCP(Supreme Ct. Contempt Petition)": 56,
  "SCCP(Supreme Ct. Cr. Contempt Petition)": 317,
  "SCMP(Supreme Ct. Cr. Misc. Petition)": 315,
  "SCMP(Supreme Ct. Misc. Petition)": 54,
  "SCTP(Supreme Ct. Transfer Petition)": 61,
  "SCTP(Supreme Ct. Transfer Petition(CR))": 333,
  "SLP(Supreme Ct. Cr. Special Leave Petition)": 313,
  "SLP(Supreme Ct. Special Leave Petition)": 52,
  "SMAP(Cr. Suo-Motu Application)": 304,
  "SMCP(Cr. Suo-Motu Contempt Petn.)": 307,
  "SMCPC(Civil Suo Motu Contempt Petition)": 347,
  "SMP(Suo-Moto Petition)": 59,
  "SMP(Suo-Motu Cr.PIL)": 336,
  "SMPIL(Suo Motuo PIL)": 65,
  "SMRN(Cr. Suo-Motu Revision Appin.)": 306,
  "SMWP(Cr. Suo-Motu Writ Petition)": 305,
  "SMWP(Suo Motu Writ Petition)": 64,
  "SOMO(Cr. Suo-Motu Petition)": 303,
  "SPLCA(Special Civil Application)": 17,
  "STR(SALES TAX REFERENCE)": 551,
  "STXA(SALES TAX APPEAL)": 673,
  "TXA(Tax Appeal)": 14,
  "WP(Writ Petition)": 1,
  "WP(Cr.Writ Petition)": 308,
  "WPA(WRIT PETITION-AURANGABAD)": 45,
  "WPG(WRIT PETITION-GOA)": 46,
  "WPN(WRIT PETITION-NAGPUR)": 47,
  "XFER(TRANSFER MATTER)": 44,
  "XOB(Cross Objection Stamp)": 42
} as const;


export const GOA_BOMBAY_HIGH_COURT_CASE_TYPES_VALUE_MAPPING = {
  // Existing mappings (retained)
  "AAR(Appln. for Appointment of Arbitrator)": 1,
  "AELEP(Application in Election Petition)": 2,
  "AO(Appeal From Order)": 3,
  "ARA(Arbitration Application)": 4,
  "ARP(Arbitration Petition)": 5,
  "AS(Admiralty Suit)": 43,
  "AUA(Appeal Under Arbitration Act)": 6,
  "AUCPC(Appeal Under City of Panaji Corporation Act)": null,
  "AUE(Appeal Under E.S.I.)": 7,
  "AUEC(Appeal Under Employees Compensation)": 32,
  "AUFEM(Appeal Under Foreign Exchange Management Act)": null,
  "AUPML(Appeal U/S 42 of Prevention of Money Laundering Act)": null,
  "AUSFC(Appeal Under State Financial Corporation Act)": null,
  "AUW(Appeal Under Workmens Compensation Act)": null,
  "CA(Civil Application)": 9,
  "CAPL(Contempt Appeal)": 10,

  // New mappings from images
  "CAREV(Civil Application (Review))": 11,
  "COA(Company Appeal)": 12,
  "COAP(Company Application)": 13,
  "COAPM(Company Application (Main))": 40,
  "COMPP(Commercial Appeal)": 53,
  "COMP(COMPLAINTS (IN COMPANY PETITION))": 55,
  "CONF(Confirmation Case)": 301,
  "CONP(Criminal Contempt Petition)": 302,
  "COP(Company Petition)": 14,
  "CP(Contempt Petition)": 15,
  "CPCRM(Criminal Contempt Petition (Main))": 319,
  "CPM(Contempt Petition (Main))": 41,
  "CRA(Civil Revision Application)": 16,
  "CREF(Civil References)": 17,
  "CREVA(Criminal Review Application)": 320,
  "CRIA(Criminal Appeal)": 304,
  "CRIR(Criminal Revision Application)": 305,
  "CRMA(Criminal Misc. Application)": 306,
  "CRMAB(Criminal Application ( Bail ))": 310,
  "CRMAM(Criminal Application ( Main ))": 311,
  "CRREF(Criminal Reference Application)": 312,
  "CRXFA(Criminal transfer application)": 316,
  "CS(Civil Suit)": 18,
  "CUSA(Custom Appeal)": 36,
  "EA(Execution Application)": 38,
  "ELEP(Election Petition)": 19,
  "EXA(Excise Appeal)": 37,
  "EXAP(Excise Application)": 20,
  "FA(First Appeal)": 21,
  "ITA(Income Tax Appeal)": 22,
  "LPA(Letter Patent Appeal)": 23,
  "MCA(Misc.Civil Application)": 24,
  "MCAM(Misc.Civil Application (Main))": 42,
  "PILCW(PIL Criminal Writ Petition)": 318,
  "PILSM(Public Interest Litigation (Suo Motu))": 44,
  "PILWP(Public Interest Litigation WP)": 25,
  "PROP(Probate Petition)": 48,
  "RUCA(Reference Application Under Customs Act)": 26,
  "RUIT(Reference Under Income Tax Act)": 27,
  "RUSTA(REFERENCE UNDER SALES TAX ACT)": 51,
  "SA(Second Appeal)": 28,
  "SMCMA(SUO MOTU CRIMINAL MISC. APPLICATION)": 315,
  "SMCMM(SUO MOTU CRIMINAL MISCELLANEOUS (MAIN))": 317,
  "SMCP(Suo Motu Contempt Petition)": 29,
  "SMCR(Suo Motu Criminal Revision)": 313,
  "SMCRC(Suo Motu Criminal Contempt Petition)": 309,
  "SMCWP(SUO MOTU CRIMINAL WRIT PETITION)": 314,
  "SMWP(Suo Motu Writ Petition)": 30,
  "STA(Stamp Number (Appln.))": 31,
  "STM(Stamp Number Main)": 50,
  "STXA(Service Tax Appeal)": 49,
  "TACR(Criminal Transfer Appeal)": 307,
  "TMA(Trade Marks Appeal)": 323,
  "TP(Testamentary Petition)": 321,
  "TRA(Tax Revision Application)": 52,
  "TXA(Tax Appeal)": 32,
  "WP(Writ Petition)": 33,
  "WPCR(Criminal Writ Petition)": 308,
  "WTR(Wealth Tax Reference)": 47,
  "XFA(Transfer Application)": 39,
  "XFER(Transfer Matter)": 34,
  "XOB(Cross Objection)": 35
} as const;

 

export const SPECIAL_BOMBAY_HIGH_COURT_CASE_TYPES_VALUE_MAPPING = {
  // Existing mappings (retained)
  "COMP(FOR COMPLIANCE)": 758,
  "SPAP(SpI. Court Arbitration Petition)": 693,
  "SPCC(SpI. Court Counter Claim)": 756,
  "SPCO(SpI. Court Chamber Order)": 708,
  "SPCP(SpI. Court Contempt Petition)": 689,
  "SPCR(SpI. Court Custodian Report)": 686,
  "SPCS(SpI. Court Chamber Summons)": 683,
  "SPEX(SpI. Court Execution Application)": 691,
  "SPGR(SpI. Court Gamishee Notice)": 681,
  "SPIA(INTERIM APPLICATION)": 757,
  "SPIP(SpI. Court Insolvency Petition)": 690,
  "SPMA(SpI. Court Misc. Application)": 678,
  "SPMACR(SpI. Court Misc. Application Criminal)": 759,
  "SPMP(SpI. Court Misc Petition)": 679,
  "SPNM(SpI. Court Notice of Motion)": 682,
  "SPPR(SpI. Court Preciepe)": 687,

  // New mappings from image
  "SPRA(Spl. Court Remand Application)": 688,
  "SPRP(Spl. Court Review Petition)": 717,
  "SPRR(Spl. Court Court Receiver Report)": 694,
  "SPS(Spl. Court Suits)": 680,
  "SPSC(Spl. Court Spl. Case)": 684,
  "SPSD(Spl. Court Suo Moto Direction)": 728,
  "SPSJ(Spl. Court Summons for Judgment)": 695,
  "SPSMP(Suo Motu Petition)": 760,
  "SPSN(Spl. Court Show Cause Notice)": 685,
  "SPTN(Spl. Court Third Party Notice)": 696,
  "SPUR(Spl. Court Audit Report)": 692
} as const;

 

export const ORIGINAL_SIDE_BOMBAY_HIGH_COURT_CASE_TYPES_VALUE_MAPPING = {
  // Existing mappings (retained)
  "ADMS(ADMIRALTY SUITS)": 502,
  "AEP(APPLN. IN ELECTION PETITION)": 606,
  "AITR(AGRICULTURAL INCOME TAX REFERENCE)": 544,
  "APP(APPEALS)": 565,
  "ARAPP(ARBITRATION APPEAL)": 620,
  "ARBAP(ARBITRATION APPLICATION)": 511,
  "ARBP(ARBITRATION PETITION)": 510,
  "ARBS(ARBITRATION SUITS)": 508,
  "ASWP(APPELLATE SIDE WRIT PETITION)": 621,
  "AURWP(WRIT PETITION (AURANGABAD))": 622,
  "AW(AWARDS)": 608,
  "BIFR(BIFR)": 656,
  "CA(COMPANY APPLICATION)": 564,
  "CAA(COMPANY APPLICATION IN APPEAL)": 701,
  "CAPP(CHARTERED ACCOUNTANT APPEAL)": 671,
  "CAR(CHARTERED A/C REFERENCE)": 545,

  // New mappings from images
  "CARAP(Commercial Arbitration Application)": 738,
  "CARBA(Commercial Arbitration Appeal)": 745,
  "CARBP(Commercial Arbitration Petition)": 743,
  "CASE(CASE)": 623,
  "CC(COUNTER CLAIM)": 507,
  "CCP(COUNTER CLAIM(PARSI))": 711,
  "CCPC(Criminal Cont. Petn.(Company))": 714,
  "CEA(CENTRAL EXCISE APPLICATION)": 536,
  "CER(CENTRAL EXCISE REFERENCE)": 543,
  "CEXA(CENTRAL EXCISE APPEAL)": 624,
  "CHOOL(CHAMBER ORDER LODG.(COND.OF DELAY))": 611,
  "CHOIN(CHAMBER ORDER IN INSOLVECY)": 909,
  "CHOL(CHAMBER ORDER)": 610,
  "CHS(CHAMBER SUMMONS)": 586,
  "CHSCA(Chamber Summons in Commercial Appellate Division matters)": 750,
  "CHSCD(Chamber Summons in Commercial Division matters)": 749,
  "CHSP(CHAMBER SUMMONS (PROTHONOTARY))": 625,
  "CHSPM(CHAMBER SUMMONS(PARSI SUITS))": 626,
  "CHSW(CHAMBER SUMMONS IN WRIT PETITION.)": 597,
  "CN(CONTEMPT NOTICE)": 589,
  "CNPCP(CONTEMPT PETITION(COMPANY PETN.))": 576,
  "CNW(CONTEMPT NOTICE(WRIT PETITION))": 600,
  "COAPP(COMPANY APPEAL)": 577,
  "COEX(CONTEMPT PETITION IN EXECUTION)": 583,
  "COI(Chamber Order(Insolvency))": 719,
  "COMAP(Commercial Appeal)": 739,
  "COMAS(COMMERCIAL ADMIRALTY SUITS)": 758,
  "COMEX(COMMERCIAL EXECUTION APPLICATION)": 755,
  "COMIP(COMMERCIAL INTELLECTUAL PROPERTY RIGHTS SUITS)": 759,
  "COMMP(COMMERCIAL MISCELLANEOUS PETITION)": 761,
  "COMP(COMPLAINTS (IN COMPANY PETITION))": 604,
  "COMS(Commercial Suit)": 742,
  "COMSS(COMMERCIAL SUMMARY SUITS)": 757,
  "CONP(CONTEMPT PETITION)": 569,
  "CONPP(CONTEMPT PETITION IN PIL)": 729,
  "CONPW(CONTEMPT PETITION IN WRIT PETITION)": 574,
  "CONTP(CONTEMPT PETITION (TP))": 674,
  "COPP(CONTEMPT PETITION IN PARSI)": 627,
  "CP(COMPANY PETITION)": 563,
  "CPCAD(Contempt Petition in Commercial Appellate Division matters)": 754,
  "CPCD(Contempt Petition in Commercial Division matters)": 753,
  "CPIN(Civil Contempt Petition(INPT))": 705,
  "CPP(Company Partnership Petition)": 736,
  "CPTP(Criminal Contempt Petition in TP)": 697,
  "CRPIN(Criminal Contempt Petition(INPT))": 706,
  "CRR(Court Receiver Report)": 675,
  "CSD(COMPANY SUMMONS FOR DIRECTION)": 699,
  "CSP(COMPANY SCHEME PETITION)": 700,
  "CSR(COMPANY SECRETARY REFERENCE)": 555,
  "CST(CHAMBER SUMMONS (TESTAMENTARY))": 666,
  "CTDA(CHARTERED ACCOUNTANTS APPLICATION.)": 534,
  "CTS(Caveat In Testamentry)": 725,
  "CUAPP(CUSTOM APPEAL)": 628,
  "CUSA(CUSTOMS APPLICATION LODGING)": 629,
  "CUSAL(CUSTOM APPLICATION LODGING.)": 535,
  "CUSTA(CUSTOMS ACT APPLICATION.)": 533,
  "CUSTD(CUSTOM DUTY APPLICATION)": 538,
  "CUSTP(CUSTODY PETITION)": 522,
  "CUSTR(CUSTOM DUTY REFERENCE)": 546,
  "CVT(CEVEAT)": 630,
  "DM(DISCIPLINARY MATTERS)": 631,
  "DNMS(DRAFT NOTICE OF MOTION (SUITS))": 632,
  "DNMW(DRAFT NOTICE OF MOTION (WRIT PETITION))": 633,
  "EDA(ESTATE DUTY TAX APPLICATION)": 634,
  "EDR(ESTATE DUTY TAX REFERENCE)": 527,
  "EP(ELECTION PETITION)": 509,
  "EPTR(EXCESS PROFIT TAX REFERENCE)": 553,
  "ETR(EXPENDITURE TAX REFERENCE)": 554,
  "EXA(EXECUTION APPLICATION)": 609,
  "EXDA(EXCISE DUTY APPLICATION)": 539,
  "EXDR(EXCISE DUTY REFERENCE)": 549,
  "FAP(FOREIGN ADOPTION PETITION)": 512,
  "FEMA(FEMA APPEAL)": 670,
  "GCA(GOLD CONTROL APPLICATION)": 528,
  "GCR(GOLD CONTROL REFERENCE)": 548,
  "GP(GUARDIANSHIP PETITION.)": 516,
  "GRN(GUARNISHEE NOTICE)": 591,
  "GTA(GIFT TAX APPLICATION)": 532,
  "GTR(GIFT TAX REFERENCE)": 635,
  "GTXA(GIFT TAX APPEAL)": 602,
  "IA(INTERIM APPLICATION)": 907,
  "IAP(INTERIM ARBITRATION APPLICATION)": 582,
  "IAP(INDIAN ADOPTION PETITION)": 526,
  "IARBP(INTERIM ARBITRATION PETITION)": 521,
  "IC(Indian Companies)": 737,
  "ICONP(INTERIM CONTEMPT PETITION)": 570,
  "ICP(INT.CUST.PETITION.)": 517,
  "IDA(INSOLVENCY DISCHARGE APPLICATION)": 660,
  "IGP(INDIAN GUARDANSHIP PETITION)": 658,
  "ILP(INTERIM LUNANCY PETITION)": 636,
  "IMGP(INTERIM GUARDIAN PETITION)": 523,
  "IMHA(INTERIM MENTAL HEALTH ACT PETITION)": 525,
  "IMP(INTERIM MISC. PETITION)": 520,
  "INAP(Intervention Application)": 702,
  "INOT(INSOLVENCY NOTICE)": 567,
  "INPT(INSOLVENCY PETITION)": 514,
  "INSA(INSURANCE ACT)": 637,
  "INSP(INSOLVENCY PETITION)": 566,
  "IP(INT.PETITION.)": 638,
  "IPA(In Person Application)": 734,
  "IPMP(INTERIM PARSI MATRIMONIAL PETITION)": 639,
  "IRN(INSOLVENCY RULE NISI)": 659,
  "IRXA(INTEREST TAX APPEAL)": 617,
  "ITA(INCOME TAX APPLICATION)": 530,
  "ITR(INCOME TAX REFERENCE)": 542,
  "ITXA(INCOME TAX APPEAL(IT))": 601,
  "JO(JUDGES ORDER)": 664,
  "JOI(Judges Order(Insolvency))": 721,
  "JOT(JUDGES ORDER (TESTAMENTARY))": 552,
  "JOW(JUDGES ORDER (WRIT PETITION))": 672,
  "LAR(LAND ACQUISITION REFERENCE)": 613,
   // New mappings from latest images
  "LP(LUNANCY PETITION)": 519,
  "LPETN(LEAVE PETITION)": 556,
  "LPW(LEAVE PETITION(WRIT))": 713,
  "MAPP(MISC.APPLICATION)": 614,
  "MCA(MISC.COM.APP)": 640,
  "MERC(MAHA. ELECTRICITY REGULATORY COMM.)": 615,
  "MHA(MENTAL HEALTH ACT PETITION)": 524,
  "MJS(MATRIMONIAL SUITS)": 503,
  "MP(MISC.PETITION.)": 515,
  "MPIN(Misc. Petition for leave)": 703,
  "MPP(MISC. PARSI PETITION)": 641,
  "MPT(MISC PETITION IN T and I J)": 562,
  "MS(MISFEASONS SUMMONSES)": 642,
  "MTA(MISC. TESTAMENTARY APPLN.)": 616,
  "MVXA(Mah. Value Added Tax Appeal)": 722,
  "N(NOTICE)": 587,
  "NAGWP(WRIT PETITION (NAGPUR))": 643,
  "NMA(NOTICE OF MOTION (APPEALS))": 585,
  "NMC(NOTICE OF MOTION (COMPANY))": 644,
  "NMCA(Notice of Motion in Commercial Appellate Division matters)": 748,
  "NMCD(Notice of Motion in Commercial Division matters)": 747,
  "NMIS(NOTICE OF MOTION (INSOLVENCY))": 645,
  "NMISA(NM FOR SETTING ASIDE INSOL.NOTICE)": 661,
  "NMSP(NOTICE OF MOTION (PARSI SUIT))": 646,
  "NMT(NOTICE OF MOTION (TESTAMENTARY))": 665,
  "NMW(NOTICE OF MOTION (WRIT PETITION))": 596,
  "OAR(OFFICIAL ASSIGNEES REPORT)": 662,
  "OLR(Official Liquidator Report)": 716,
  "ORGS(ORGINATING SUMMONS)": 590,
  "OTS(Obj. to Scheme(Company))": 715,
  "PCN(PARSI CONTEMPT NOTICE OF MOTION)": 647,
  "PEXA(PARSI EXECUTION APPLICATION)": 731,
  "PIL(PUBLIC INTEREST LITIGATION)": 668,
  "PMA(PARSI MISC. APPLICATION)": 730,
  "PMP(PARSI MATRIMONIAL PETITION)": 648,
  "PMTP(PARSI MAINTENANCE PETITION)": 669,
  "PN(PERJURY NOTICE)": 592,
  "PNW(PERJURY NOTICE ( WRIT PETITION))": 599,
  "PP(PAUPER PETITION)": 501,
  "PPA(PAUPER PETITION (APPEAL))": 580,
  "PPET(PARSI PETITION)": 710,
  "PPIN(Protection Petition(INPT))": 723,
  "PPT(PAUPER PETITION (TESTAMENTARY))": 667,
  "PRJP(PERJURY PETITION)": 581,
  "PS(PARSI SUITS)": 505,
  "PSC(PETI.FOR LEAVE TO APPEAL TO THE SUP.CRT)": 607,
  "RA(RESTORATION APPLICATION)": 727,
  "RAL(REFERENCE APPLICATION LODGING)": 649,
  "RCW(Rejected Case(OS-WP))": 677,
  "REP(REPORT)": 650,
  "RP(REVIEW PETITION)": 557,
  "RPA(REVIEW PETITION(APPEAL))": 558,
  "RPC(REVIEW PETITION (COMPANY))": 579,
  "RPCA(Review Petition in Commercial Appellate Division matters)": 752,
  "RPCD(Review Petition in Commercial Division matters)": 751,
  "RPE(Recrimination Petition)": 712,
  "RPIA(REVIEW PETITION IN IA)": 908,
  "RPIN(Review Petition for Leave(INPT))": 704,
  "RPP(REVIEW PETITION(PIL))": 732,
  "RPPS(Review Petition in Parsi Suit)": 718,
  "RPW(REVIEW PETITION (WRIT PETITION))": 568,
  "RTP(REVIEW PETITION (TESTAMENTARY))": 578,
  "S(SUITS)": 504,
  "SAPP(SEBI APPEAL)": 612,
  "SCN(SHOW CAUSE NOTICE)": 588,
  "SCNCP(SHOW CAUSE NOTICE (COMPANY))": 619,
  "SCNIN(Show Cause Notice(INPT))": 707,
  "SCNP(SHOW CAUSE NOTICE IN CPTP)": 698,
  "SCNTP(SHOW CAUSE NOTICE (TESTA.PETN.))": 618,
  "SCNW(SHOW CAUSE NOTICE (WRIT PETITION))": 598,
  "SUSUMMONSES FOR JUDGEMENT)": 595,
  "SMC(SUO MOTO CONTEMPT PETITION)": 573,
  "SMCN(SUO MOTO CONTEMPT NOTICE)": 593,
  "SMCP(SUO MOTO CRIMINAL CONTEMPT PETITION)": 571,
  "SMCR(SUO MOTO CIVIL CONTEMPT REFERENCE)": 572,
  "SMN(SUO MOTO NOTICE)": 594,
  "SMP(SUO MOTO PIL)": 726,
  "SMSN(SUO MOTO SHOW CAUSE NOTICE)": 724,
  "SMWP(SUO MOTO IN WRIT PETITION)": 575,
  "SPAR(SPECIAL CASE IN ARBITRATION PETN/APPL)": 605,
  "SPTA(SUPER PROFIT TAX APPLICATIONS)": 540,
  "SPTR(SUPER PROFIT TAX REFERENCE)": 550,
  "SS(SUMMARY SUITS)": 506,
  "STA(SALES TAX APPLICATIONS)": 531,
  "STAPP(SUR TAX APPEAL)": 663,
  "STR(SALES TAX REFERENCE)": 551,
  "STXA(SALES TAX APPEAL)": 673,
  "SURTA(SUR TAX APPLICATION)": 537,
  "SURTR(SUR TAX REFERENCE)": 651,
  "TC(COMPLAINTS IN TESTAMENTARY MATTERS)": 760,
  "TD(Transfer Decree)": 709,
  "TP(TESTAMENTARY PETITION)": 561,
  "TPAC(Third Party Applications for CC)": 733,
  "TPN(THIRD PARTY NOTICE)": 652,
  "TRP(TRUST PETITION)": 518,
  "TRS(TRANSFERRED SUIT FROM OTHER COURTS)": 653,
  "TS(TESTAMENTARY SUITS)": 654,
  "WILL(Will)": 735,
  "WP(WRIT PETITION)": 560,
  "WSCCL(WRITTEN STATMENT amp COUNTER-CLAIM)": 655,
  "WTA(WEALTH TAX APPLICATION)": 529,
  "WTR(WEALTH TAX REFERENCE)": 541,
  "WTXA(WEALTH TAX APPEAL)": 603
} as const;

